import { useEffect,useMemo,useState } from "react";
import {CalendarDays,CheckCircle2,Clock3,FileUp,MapPin,MessageSquareText,Plus,RefreshCw,Search,Users,XCircle,ShieldCheck,AlertTriangle} from "lucide-react";
import {toast} from "sonner";
import {useAuth} from "@/contexts/AuthContext";
import {fetchProfiles} from "@/services/profileService";
import {fetchLeadOptions} from "@/services/leadService";
import {completeSchedule,createSchedule,fetchScheduleFiles,fetchSchedules,updateSchedule,uploadScheduleFile,fetchMeetingRule,fetchCalendarStatus,checkCalendarAvailability,syncScheduleToCalendar} from "@/services/scheduleService";

const TYPES=[["site_visit","Site Visit"],["customer_home","Customer Home Meeting"],["office_meeting","Office Meeting"],["measurement_visit","Measurement Visit"],["project_review","Project Review"],["material_discussion","Material Discussion"],["video_meeting","Video Meeting"],["design_presentation","Design Presentation"],["estimate_discussion","Estimate Discussion"],["phone_discussion","Phone Discussion"],["whatsapp_discussion","WhatsApp Discussion"],["follow_up","Follow-up"],["other","Other"]];
const FEEDBACKS=["Interested","Need Discussion","Budget Issue","Design Discussion","Follow-up Required","Not Interested","Ready for Next Step"];
const localInput=(d=new Date())=>{const p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const bounds=(d)=>{const s=new Date(d);s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+1);return{from:s.toISOString(),to:e.toISOString()}};
const label=v=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const localDate=()=>{const d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const slotIso=(date,h,m)=>{const d=new Date(`${date}T00:00:00`);d.setHours(h,m,0,0);return d.toISOString()};
const overlaps=(a,b,s,e)=>new Date(a).getTime()<new Date(e).getTime()&&new Date(b).getTime()>new Date(s).getTime();
const fmtTime=iso=>new Date(iso).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"});

export default function SchedulePage(){
 const {profile}=useAuth();const [rows,setRows]=useState([]),[leads,setLeads]=useState([]),[team,setTeam]=useState([]),[selected,setSelected]=useState(null),[files,setFiles]=useState([]),[loading,setLoading]=useState(true),[view,setView]=useState("today"),[query,setQuery]=useState(""),[showCreate,setShowCreate]=useState(false),[saving,setSaving]=useState(false);
 const [calendar,setCalendar]=useState(null),[rule,setRule]=useState(null),[slots,setSlots]=useState([]),[checking,setChecking]=useState(false);
 const [form,setForm]=useState({lead_id:"",title:"",meeting_type:"follow_up",mode:"digital",status:"scheduled",priority:"normal",date:localDate(),location_address:"",meeting_link:"",description:"",owner_id:"",manager_id:"",director_id:"",customer_email:""});
 const load=async()=>{setLoading(true);try{const n=new Date();const b=view==="today"?bounds(n):{from:new Date(n.getFullYear(),n.getMonth(),n.getDate()).toISOString(),to:new Date(n.getFullYear(),n.getMonth(),n.getDate()+7).toISOString()};const [s,l,p,cal]=await Promise.all([fetchSchedules(b),fetchLeadOptions(),fetchProfiles(),fetchCalendarStatus()]);setRows(s);setLeads(l);setTeam(p);setCalendar(cal)}catch(e){toast.error(e.message||"Could not load schedules")}finally{setLoading(false)}};
 useEffect(()=>{load()},[view]);
 useEffect(()=>{if(showCreate)fetchMeetingRule(form.meeting_type,form.mode).then(setRule).catch(e=>toast.error(e.message))},[showCreate,form.meeting_type,form.mode]);
 const managers=useMemo(()=>team.filter(p=>p.role==="rm"&&p.is_active!==false),[team]);
 const directors=useMemo(()=>team.filter(p=>(p.is_admin===true||p.role==="admin")&&p.is_active!==false),[team]);
 useEffect(()=>{if(showCreate&&rule?.participant_rule?.director&&!form.director_id&&directors[0])setForm(f=>({...f,director_id:directors[0].id}))},[showCreate,rule,directors]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(s=>!q||[s.title,s.location_address,s.owner?.full_name,s.meeting_type,s.status].filter(Boolean).join(" ").toLowerCase().includes(q))},[rows,query]);
 const stats={total:rows.length,pending:rows.filter(s=>["scheduled","confirmed","pending_confirmation"].includes(s.status)).length,completed:rows.filter(s=>s.status==="completed").length,outcome:rows.filter(s=>s.status==="completed"&&!s.feedback&&!s.remarks).length};
 const checkAvailability=async()=>{
  if(!form.owner_id||!form.date)return toast.error("Meeting owner and date are required");
  if(!calendar?.configured||!calendar?.master_calendar_configured)return toast.error("Google Calendar is not fully connected yet");
  const managersToCheck=rule?.participant_rule?.manager==="any"?(form.manager_id?managers.filter(p=>p.id===form.manager_id):managers):[];
  const directorIds=rule?.participant_rule?.director?(form.director_id?[form.director_id]:directors.slice(0,1).map(p=>p.id)):[];
  if(rule?.participant_rule?.manager==="any"&&!managersToCheck.length)return toast.error("No manager is configured");
  const combos=(rule?.participant_rule?.manager==="any"?managersToCheck:[null]).map(m=>[form.owner_id,...(m?[m.id]:[]),...directorIds].filter(Boolean));
  setChecking(true);setSlots([]);
  try{
    const dayStart=slotIso(form.date,9,0),dayEnd=slotIso(form.date,20,0),duration=rule?.default_duration_minutes||30,buffer=rule?.travel_buffer_minutes||0;
    const results=await Promise.all(combos.map(async ids=>({ids,data:await checkCalendarAvailability({start:dayStart,end:dayEnd,userIds:ids})})));
    const found=[];
    for(const r of results)for(let h=9;h<20;h++)for(let m=0;m<60;m+=30){
      const start=slotIso(form.date,h,m),end=slotIso(form.date,h,m+duration),safeStart=new Date(new Date(start).getTime()-buffer*60000).toISOString(),safeEnd=new Date(new Date(end).getTime()+buffer*60000).toISOString();
      if(new Date(end)>new Date(dayEnd))continue;
      if(!(r.data?.busy||[]).some(b=>overlaps(b.start,b.end,safeStart,safeEnd)))found.push({start,end,participantIds:r.ids});
    }
    const unique=[...new Map(found.map(s=>[s.start+"-"+s.end,s])).values()];setSlots(unique);
    if(!unique.length)toast.info("No common free slot found for the selected team");
  }catch(e){toast.error(e.message||"Availability check failed")}finally{setChecking(false)}
};
const save=async()=>{
  const chosen=slots.find(s=>s.selected);if(!chosen)return toast.error("Select an available slot first");
  if(form.mode==="physical"&&!form.location_address.trim())return toast.error("Physical schedule needs a site/location");
  setSaving(true);
  try{
    const created=await createSchedule({lead_id:form.lead_id||null,title:form.title,meeting_type:form.meeting_type,mode:form.mode,status:"scheduled",priority:form.priority,start_at:chosen.start,end_at:chosen.end,timezone:"Asia/Kolkata",location_address:form.mode==="physical"?form.location_address:null,meeting_link:form.mode==="digital"?form.meeting_link||null:null,description:form.description||null,owner_id:form.owner_id,assigned_by:profile?.id||null,customer_email:form.customer_email||null},chosen.participantIds,chosen.participantIds);
    if(calendar?.configured&&calendar?.master_calendar_configured){await syncScheduleToCalendar(created.id);toast.success("Schedule created and synced to Google Calendar")}else toast.success("Schedule created; Google Calendar connection is pending");
    setShowCreate(false);setSlots([]);load();
  }catch(e){toast.error(e.code==="SLOT_CONFLICT"?"That slot was just booked. Please select another slot.":e.message||"Could not create schedule")}finally{setSaving(false)}
};
 const open=async(r)=>{setSelected(r);try{setFiles(await fetchScheduleFiles(r.id))}catch{setFiles([])}};
 const update=async(p)=>{if(!selected)return;try{const u=p.status==="completed"?await completeSchedule(selected.id,p):await updateSchedule(selected.id,p);setSelected(u);toast.success("Schedule updated");load()}catch(e){toast.error(e.message||"Update failed")}};
 const upload=async(file)=>{if(!file||!selected)return;try{const f=await uploadScheduleFile(selected.id,selected.lead_id,file,{source:selected.mode==="physical"?"field_visit":"employee"});setFiles(x=>[f,...x]);toast.success("File uploaded")}catch(e){toast.error(e.message||"Upload failed")}};
 return <section className="p-5 lg:p-8 max-w-[1500px] mx-auto">
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4 mb-6"><div><div className="text-xs uppercase tracking-[0.18em] text-orange-600 font-semibold">Customer Operations</div><h1 className="text-2xl lg:text-3xl font-bold text-slate-900 mt-1">Schedule</h1><p className="text-sm text-slate-500 mt-1">Meetings, availability, feedback and next actions.</p></div><div className="flex gap-2"><button onClick={load} className="h-10 px-3 rounded-lg border bg-white"><RefreshCw className="w-4 h-4"/></button><button onClick={()=>setShowCreate(true)} className="h-10 px-4 rounded-lg bg-blue-700 text-white font-semibold flex items-center gap-2"><Plus className="w-4 h-4"/>New Schedule</button></div></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-6">{[["Total",stats.total,CalendarDays],["Pending",stats.pending,Clock3],["Completed",stats.completed,CheckCircle2],["Outcome Pending",stats.outcome,MessageSquareText]].map(([n,v,I])=><div key={n} className="bg-white border border-slate-200 rounded-xl p-4"><div className="flex items-center gap-2 text-slate-500 text-xs uppercase tracking-wider"><I className="w-4 h-4"/>{n}</div><div className="text-2xl font-bold mt-2">{v}</div></div>)}</div>
  <div className="bg-white border border-slate-200 rounded-xl overflow-hidden"><div className="p-4 border-b flex flex-col lg:flex-row gap-3 justify-between"><div className="flex gap-2"><button onClick={()=>setView("today")} className={`px-3 py-2 rounded-lg text-sm font-medium ${view==="today"?"bg-slate-900 text-white":"bg-slate-100"}`}>Today</button><button onClick={()=>setView("week")} className={`px-3 py-2 rounded-lg text-sm font-medium ${view==="week"?"bg-slate-900 text-white":"bg-slate-100"}`}>Next 7 Days</button></div><div className="relative max-w-sm w-full"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer, meeting, owner..." className="w-full h-9 pl-9 pr-3 border rounded-lg text-sm"/></div></div>{loading?<div className="p-12 text-center text-slate-400">Loading schedules…</div>:filtered.length===0?<div className="p-12 text-center text-slate-400">No schedules found.</div>:<div className="divide-y">{filtered.map(s=><button key={s.id} onClick={()=>open(s)} className="w-full text-left p-4 hover:bg-slate-50 grid lg:grid-cols-[150px_1fr_180px_140px] gap-3 items-center"><div><div className="font-semibold">{new Date(s.start_at).toLocaleDateString("en-IN",{day:"2-digit",month:"short"})}</div><div className="text-xs text-slate-500">{new Date(s.start_at).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}</div></div><div><div className="font-semibold">{s.title}</div><div className="text-xs text-slate-500 mt-1">{label(s.meeting_type)} · {label(s.mode)}{s.location_address?` · ${s.location_address}`:""}</div></div><div className="text-sm text-slate-600">{s.owner?.full_name||"Unassigned"}</div><div><span className={`inline-flex px-2 py-1 rounded-full text-xs font-semibold ${s.status==="completed"?"bg-emerald-50 text-emerald-700":s.status.includes("cancel")||s.status.includes("no_show")?"bg-rose-50 text-rose-700":"bg-blue-50 text-blue-700"}`}>{label(s.status)}</span></div></button>)}</div>}</div>
  {showCreate&&<div className="fixed inset-0 z-50 bg-black/40 p-4 flex items-center justify-center"><div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-auto shadow-2xl"><div className="p-5 border-b flex justify-between"><div><h2 className="text-lg font-bold">New Schedule</h2><p className="text-xs text-slate-500">Select required participants, check common availability, then book.</p></div><button onClick={()=>setShowCreate(false)}><XCircle className="w-5 h-5 text-slate-400"/></button></div><div className="p-5 grid md:grid-cols-2 gap-4">
   <label className="text-sm font-medium">Lead<select value={form.lead_id} onChange={e=>setForm({...form,lead_id:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3"><option value="">Select lead</option>{leads.map(l=><option key={l.id} value={l.id}>{l.name} — {l.phone}</option>)}</select></label>
   <label className="text-sm font-medium">Meeting Owner<select value={form.owner_id} onChange={e=>setForm({...form,owner_id:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3"><option value="">Select employee</option>{team.filter(p=>p.is_active!==false).map(p=><option key={p.id} value={p.id}>{p.full_name||p.email}</option>)}</select></label>
   <label className="text-sm font-medium md:col-span-2">Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3" placeholder="Rahul Kumar — Site Visit"/></label>
   <label className="text-sm font-medium">Type<select value={form.meeting_type} onChange={e=>setForm({...form,meeting_type:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3">{TYPES.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>
   <label className="text-sm font-medium">Mode<select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3"><option value="physical">Physical</option><option value="digital">Digital</option></select></label>
   <label className="text-sm font-medium">Meeting Date<input type="date" value={form.date} onChange={e=>{setForm({...form,date:e.target.value});setSlots([])}} className="mt-1 w-full h-10 border rounded-lg px-3"/></label>
   <label className="text-sm font-medium">Manager<select value={form.manager_id} onChange={e=>{setForm({...form,manager_id:e.target.value});setSlots([])}} className="mt-1 w-full h-10 border rounded-lg px-3"><option value="">Any available manager</option>{managers.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label>
   {rule?.participant_rule?.director&&<label className="text-sm font-medium md:col-span-2">Director / Required Presence<select value={form.director_id} onChange={e=>{setForm({...form,director_id:e.target.value});setSlots([])}} className="mt-1 w-full h-10 border rounded-lg px-3">{directors.map(p=><option key={p.id} value={p.id}>{p.full_name} — required</option>)}</select></label>}
   {form.mode==="physical"?<label className="text-sm font-medium md:col-span-2">Site / Location<input value={form.location_address} onChange={e=>setForm({...form,location_address:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3" placeholder="Customer site address"/></label>:<label className="text-sm font-medium md:col-span-2">Meeting Link <span className="text-slate-400">(Google Meet can be generated on sync)</span><input value={form.meeting_link} onChange={e=>setForm({...form,meeting_link:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3" placeholder="Optional"/></label>}
   <div className="md:col-span-2 rounded-xl border bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><div><div className="font-semibold">Team Availability</div><div className="text-xs text-slate-500 mt-1">{calendar?.configured&&calendar?.master_calendar_configured?"Google Calendar connected — checking required calendars together.":"Google Calendar connection is pending."}</div></div><button onClick={checkAvailability} disabled={checking||!calendar?.configured||!calendar?.master_calendar_configured} className="px-4 py-2 rounded-lg bg-blue-700 text-white font-semibold disabled:opacity-50">{checking?"Checking…":"Check Available Slots"}</button></div>{slots.length>0&&<div className="mt-3 grid grid-cols-2 sm:grid-cols-4 gap-2">{slots.map((s,i)=><button key={i} onClick={()=>setSlots(x=>x.map((z,j)=>({...z,selected:j===i})))} className={s.selected?"px-3 py-2 rounded-lg border bg-blue-700 text-white text-sm font-semibold":"px-3 py-2 rounded-lg border bg-white text-sm font-semibold hover:bg-blue-50"}>{fmtTime(s.start)} – {fmtTime(s.end)}</button>)}</div>}</div>
   <label className="text-sm font-medium">Customer Email <span className="text-slate-400">(optional)</span><input value={form.customer_email} onChange={e=>setForm({...form,customer_email:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3"/></label>
   <label className="text-sm font-medium">Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label>
   <label className="text-sm font-medium md:col-span-2">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} className="mt-1 w-full border rounded-lg p-3"/></label>
  </div><div className="p-5 border-t flex justify-end gap-2"><button onClick={()=>setShowCreate(false)} className="px-4 py-2 rounded-lg border">Cancel</button><button disabled={saving||!slots.some(s=>s.selected)} onClick={save} className="px-4 py-2 rounded-lg bg-blue-700 text-white font-semibold disabled:opacity-50">{saving?"Booking…":"Confirm Schedule"}</button></div></div></div>}
  {selected&&<div className="fixed inset-0 z-50 bg-black/40 p-4 flex items-center justify-center" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="bg-white rounded-2xl w-full max-w-3xl max-h-[92vh] overflow-auto shadow-2xl"><div className="p-5 border-b flex justify-between"><div><div className="text-xs uppercase tracking-wider text-orange-600 font-semibold">{label(selected.meeting_type)}</div><h2 className="text-xl font-bold mt-1">{selected.title}</h2><div className="text-sm text-slate-500 mt-1">{new Date(selected.start_at).toLocaleString("en-IN")}</div></div><button onClick={()=>setSelected(null)}><XCircle className="w-6 h-6 text-slate-400"/></button></div><div className="p-5 space-y-5">
   <div className="grid md:grid-cols-3 gap-3"><button onClick={()=>update({status:"completed"})} className="p-3 rounded-xl border bg-emerald-50 text-emerald-700 font-semibold"><CheckCircle2 className="w-4 h-4 inline mr-2"/>Completed</button><button onClick={()=>update({status:"rescheduled"})} className="p-3 rounded-xl border bg-amber-50 text-amber-700 font-semibold"><Clock3 className="w-4 h-4 inline mr-2"/>Reschedule</button><button onClick={()=>update({status:"customer_cancelled"})} className="p-3 rounded-xl border bg-rose-50 text-rose-700 font-semibold"><XCircle className="w-4 h-4 inline mr-2"/>Customer Cancelled</button></div>
   <div><div className="text-sm font-semibold mb-2">Quick Feedback</div><div className="flex flex-wrap gap-2">{FEEDBACKS.map(n=><button key={n} onClick={()=>update({feedback_tags:[n]})} className="px-3 py-2 rounded-full border bg-slate-50 text-xs font-semibold">{n}</button>)}</div></div>
   <div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-semibold">Remarks<textarea defaultValue={selected.remarks||""} onBlur={e=>e.target.value!==selected.remarks&&update({remarks:e.target.value})} rows={4} className="mt-1 w-full border rounded-lg p-3 font-normal" placeholder="What happened?"/></label><label className="text-sm font-semibold">Customer Feedback<textarea defaultValue={selected.feedback||""} onBlur={e=>e.target.value!==selected.feedback&&update({feedback:e.target.value})} rows={4} className="mt-1 w-full border rounded-lg p-3 font-normal" placeholder="What did the customer say?"/></label></div>
   <div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-semibold">Next Action<input defaultValue={selected.next_action||""} onBlur={e=>e.target.value!==selected.next_action&&update({next_action:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3 font-normal" placeholder="Create estimate / follow-up call"/></label><label className="text-sm font-semibold">Next Action Date<input type="date" defaultValue={selected.next_action_date||""} onBlur={e=>e.target.value!==selected.next_action_date&&update({next_action_date:e.target.value})} className="mt-1 w-full h-10 border rounded-lg px-3 font-normal"/></label></div>
   <div className="border-t pt-4"><div className="flex items-center justify-between mb-2"><div className="font-semibold">Files / Site Information</div><label className="px-3 py-2 rounded-lg border text-sm font-semibold cursor-pointer flex items-center gap-2"><FileUp className="w-4 h-4"/>Upload<input type="file" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label></div>{files.length===0?<div className="text-sm text-slate-400 py-4">No files uploaded yet.</div>:<div className="space-y-2">{files.map(f=><a key={f.id} href={f.file_url||f.drive_url||"#"} target="_blank" rel="noreferrer" className="flex items-center justify-between p-3 rounded-lg bg-slate-50 border text-sm"><span className="truncate">{f.file_name}</span><span className="text-xs text-slate-400">{label(f.source)}</span></a>)}</div>}</div>
   <div className="grid md:grid-cols-2 gap-3 text-sm text-slate-600"><div className="p-3 bg-slate-50 rounded-lg"><MapPin className="w-4 h-4 inline mr-2"/>{selected.location_address||"Digital meeting"}</div><div className="p-3 bg-slate-50 rounded-lg"><Users className="w-4 h-4 inline mr-2"/>{selected.owner?.full_name||"Unassigned"}</div></div>
  </div></div></div>}
 </section>
}
